# : Manager [[[

[mgr]
cwd = { fg = "#e4e1e9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff72b7", bg = "#ff72b7" }
marker_cut      = { fg = "#ffd8eb", bg = "#ffd8eb" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e9b9d3", bg = "#e9b9d3" }

# Count
count_copied   = { fg = "#2f1124", bg = "#ffd8eb" }
count_cut      = { fg = "#2f1124", bg = "#ffd8eb" }
count_selected = { fg = "#2a2a60", bg = "#e9b9d3" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#c1c1ff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "‚ñà", close = "‚ñà" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#c1c1ff", bold = true, bg = "#131318" }
inactive  = { fg = "#c6c4dd", bg = "#131318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c1c1ff", fg = "#2a2a60", bold = true }
normal_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Select mode
select_main = { bg = "#c6c4dd", fg = "#2f2f42", bold = true }
select_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Unset mode
unset_main = { bg = "#e9b9d3", fg = "#46263a", bold = true }
unset_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "ü≠Å", close = "ü≠†" }
sep_right = { open = "ü≠Å", close = "ü≠†" }

# Permissions
perm_type  = { fg = "#6863a5" }
perm_write = { fg = "#c4458a" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff3f9d" }
perm_sep   = { fg = "#5746ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c1c1ff", bg = "#39383f" }
progress_error  = { fg = "#ffb4ab", bg = "#39383f" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39383f" }
cand = { fg = "#c1c1ff" }
rest = { fg = "#2a2a60" }
desc = { fg = "#e4e1e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e4e1e9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#e9b9d3" }
title_warn  = { fg = "#c1c1ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#c1c1ff" }
active = { fg = "#e9b9d3", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c1c1ff" }
value  = { fg = "#e4e1e9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#c1c1ff", bg = "#2a2a60" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#c1c1ff" }
title   = {}
hovered = { fg = "#ffd8eb", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e4e1e9" }
run    = { fg = "#e4e1e9" }
footer = { fg = "#2f2f42", bg = "#c6c4dd" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e4e1e9" },
    { url = "*/", fg = "#c1c1ff" },
]

# : ]]]